apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: netwatch-cleanup-controller
    control-plane: controller-manager
  name: netwatch-cleanup-controller-metrics-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 8443
  selector:
    app.kubernetes.io/name: netwatch-cleanup-controller
    control-plane: controller-manager
