apiVersion: v1
kind: Service
metadata:
  name: netwatch-service
  labels:
    app.kubernetes.io/name: netwatch-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/name: netwatch
